from .financeiro import editar_parcela, exportar_financeiro_csv, financeiro, pagar_nota, pagar_parcela
from .api import (
    api_moradores,
    api_paginas,
    api_relatorio_almoxarifado,
    api_relatorio_calendario,
    api_relatorio_compras,
    api_relatorio_financeiro,
    api_relatorio_home,
    api_relatorio_manutencao,
    api_relatorio_moradores,
    api_relatorio_perfil,
    api_relatorio_rock,
)
from .estoque import (
    almoxarifado,
    consumo_historico,
    editar_produto,
    exportar_consumo_csv,
    exportar_estoque_csv,
    registrar_consumo,
)
from .legacy import (
    cadastro,
    calendario,
    compras,
    configurar_formularios,
    configurar_listas,
    editar_nota_compra,
    editar_os,
    gerenciar_acessos,
    home,
    lista_os,
    manutencao,
    moradores,
    perfil,
    rock,
    editar_rock,
    exportar_compras_csv,
    exportar_moradores_csv,
)
