from .financeiro import editar_parcela, exportar_financeiro_csv, financeiro, pagar_nota, pagar_parcela
from .estoque import (
    almoxarifado,
    consumo_historico,
    editar_produto,
    exportar_consumo_csv,
    exportar_estoque_csv,
    registrar_consumo,
)
from .legacy import (
    cadastro,
    calendario,
    compras,
    configurar_formularios,
    configurar_listas,
    editar_nota_compra,
    editar_os,
    gerenciar_acessos,
    home,
    lista_os,
    manutencao,
    moradores,
    perfil,
    rock,
    editar_rock,
    lotes_rock,
    ingressos_rock,
    exportar_ingressos_rock_pdf,
    comprar_rocks,
    exportar_compras_csv,
    exportar_moradores_csv,
)
