# Generated by Django 5.2.11 on 2026-03-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localarmazenamento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ssetor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
        ),
    ]
