# Generated by Django 5.2.11 on 2026-03-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_localarmazenamento_setor_produto_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ssetor',
        ),
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
            preserve_default=False,
        ),
    ]
