# Generated by Django 5.2.11 on 2026-03-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produto_ssetor_produto_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('executado_por', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='aberta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.ordemservico')),
            ],
        ),
    ]
