# Generated by Django 5.2.11 on 2026-03-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordemservico_materialutilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialutilizado',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
