# Generated by Django 5.2.11 on 2026-03-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_materialutilizado_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialutilizado',
            name='nome_material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materialutilizado',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
    ]
