# Generated by Django 5.2.11 on 2026-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_materialutilizado_nome_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='despesa_gerada',
            field=models.BooleanField(default=False),
        ),
    ]
