# Generated by Django 5.2.11 on 2026-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordemservico_despesa_gerada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialutilizado',
            name='produto',
        ),
        migrations.AlterField(
            model_name='materialutilizado',
            name='nome_material',
            field=models.CharField(default='Sem nome', max_length=200),
            preserve_default=False,
        ),
    ]
