# Generated by Django 5.2.11 on 2026-03-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_materialutilizado_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='setor',
            field=models.CharField(choices=[('compras', 'Compras'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
