# Generated by Django 5.2.11 on 2026-03-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notafiscal_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='acesso_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='acesso_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='acesso_financeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='acesso_manutencao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
