# Generated by Django 5.2.11 on 2026-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_morador_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao Financeira',
                'verbose_name_plural': 'Configuracoes Financeiras',
            },
        ),
    ]
