# Generated by Django 5.2.11 on 2026-03-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracaofinanceira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['ordem_hierarquia', 'nome']},
        ),
        migrations.AddField(
            model_name='morador',
            name='ordem_hierarquia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
