# Generated by Django 5.2.11 on 2026-03-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_morador_options_morador_ordem_hierarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_agua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_luz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
