# Generated by Django 5.2.11 on 2026-03-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracaofinanceira_valor_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
