# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_consumoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='qualidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
