# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notafiscal_quantidade_qualidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='setor_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='local_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localarmazenamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tipo_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
