# Generated by Codex on 2026-03-29

from decimal import Decimal

from django.db import migrations, models


def carregar_quartos_pesos(apps, schema_editor):
    Morador = apps.get_model('core', 'Morador')

    dados = [
        ('Cazares', '21S', 'Quarto 2º andar s/ GR', Decimal('8.75'), True),
        ('Casimiro', '12S', 'Quarto do 1º andar (maior)', Decimal('8.75'), True),
        ('Milhouse', '22S', 'Quarto 2º andar c/ GR', Decimal('8.75'), True),
        ("Mib´s", '34S', 'Quarto do 3º andar (da esquerda)', Decimal('8.75'), True),
        ('MaryKay', '31S', 'Quarto da sala', Decimal('8.00'), True),
        ('Panda', '32S', 'Quarto do 3º andar (da direita)', Decimal('8.75'), True),
        ('Calouro 04', '21D1', 'Suíte 1', Decimal('6.75'), True),
        ('Moedas', '11S', 'Quarto do 1º andar (menor)', Decimal('7.00'), True),
        ('Vijjia', '22D1', 'Quarto dividido 2º andar 1', Decimal('6.75'), True),
        ('Gru', '22D2', 'Quarto dividido 2º andar 2', Decimal('6.75'), True),
        ('Tayzmanias', '32S', 'Quarto do 3º andar (menor)', Decimal('6.75'), True),
        ('Calouro 02', '31D1', 'Quarto dividido 3º andar 1', Decimal('6.75'), True),
        ('Calouro 03', '31D2', 'Quarto dividido 3º andar 2', Decimal('6.75'), True),
        ('Vago', '21D2', 'Suíte 2', Decimal('6.75'), False),
    ]

    for apelido, codigo, quarto, peso, ativo in dados:
        morador = (
            Morador.objects.filter(apelido=apelido).first()
            or Morador.objects.filter(nome=apelido).first()
        )
        if morador is None:
            morador = Morador.objects.create(
                nome=apelido,
                apelido=apelido,
                ativo=ativo,
            )
        morador.quarto = quarto
        morador.codigo_quarto = codigo
        morador.peso_quarto = peso
        morador.ativo = ativo
        morador.save(update_fields=['quarto', 'codigo_quarto', 'peso_quarto', 'ativo'])


def reverter_quartos_pesos(apps, schema_editor):
    Morador = apps.get_model('core', 'Morador')
    Morador.objects.filter(apelido='Vago').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notafiscal_setor_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='quarto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='codigo_quarto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='peso_quarto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.RunPython(carregar_quartos_pesos, reverter_quartos_pesos),
    ]
