# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_morador_quartos_pesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
    ]
