# Generated by Codex on 2026-03-29

from decimal import Decimal
from datetime import date, timedelta

from django.db import migrations, models
import django.db.models.deletion


def _primeiro_vencimento(data_emissao):
    if data_emissao.day >= 5:
        mes = (data_emissao.replace(day=1) + timedelta(days=32)).replace(day=1)
    else:
        mes = data_emissao.replace(day=1)
    return mes.replace(day=5), mes


def criar_parcelas_existentes(apps, schema_editor):
    NotaFiscal = apps.get_model('core', 'NotaFiscal')
    NotaParcela = apps.get_model('core', 'NotaParcela')

    for nota in NotaFiscal.objects.all():
        if NotaParcela.objects.filter(nota_id=nota.id).exists():
            continue

        quantidade = nota.quantidade_parcelas or 1
        if not nota.parcelado:
            quantidade = 1
            nota.quantidade_parcelas = 1
            nota.save(update_fields=['quantidade_parcelas'])

        total = (nota.valor or Decimal('0.00')) * (nota.quantidade or 0)
        if quantidade <= 0:
            quantidade = 1

        vencimento, mes_ref = _primeiro_vencimento(nota.data_emissao)
        valor_parcela = (total / quantidade).quantize(Decimal('0.01')) if quantidade else total
        restante = total

        for idx in range(1, quantidade + 1):
            valor = valor_parcela if idx < quantidade else restante.quantize(Decimal('0.01'))
            NotaParcela.objects.create(
                nota_id=nota.id,
                numero=idx,
                valor=valor,
                vencimento=vencimento,
                mes_referencia=mes_ref,
                status='pendente',
            )
            restante -= valor
            mes_ref = (mes_ref + timedelta(days=32)).replace(day=1)
            vencimento = mes_ref.replace(day=5)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notafiscal_parcelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='quantidade_parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='NotaParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('mes_referencia', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.notafiscal')),
            ],
            options={
                'ordering': ['vencimento', 'id'],
            },
        ),
        migrations.RunPython(criar_parcelas_existentes, migrations.RunPython.noop),
    ]
