# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notaparcelas_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialutilizado',
            name='nome_material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='morador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.morador'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='data_consumo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='consumo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consumoestoque'),
        ),
    ]
