# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_materialutilizado_consumo_almox'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('nosso', 'Nosso Rock'), ('aluguel', 'Aluguel da Casa')], max_length=20)),
                ('quantidade_pessoas', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('valor_arrecadado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
