# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rock_evento_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='categoria_compra',
            field=models.CharField(default='geral', max_length=20),
        ),
    ]
