# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notafiscal_categoria_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoestoque',
            name='setor',
            field=models.CharField(choices=[('infraestrutura', 'Infraestrutura'), ('rock', 'Rock'), ('outros', 'Outros')], default='infraestrutura', max_length=20),
        ),
        migrations.AddField(
            model_name='consumoestoque',
            name='rock_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rockevento'),
        ),
    ]
