# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_consumo_setor_rockevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescontoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'unique_together': {('mes_referencia',)},
            },
        ),
        migrations.CreateModel(
            name='AjusteMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('tipo', models.CharField(choices=[('extra', 'Extra'), ('desconto', 'Desconto')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.morador')),
            ],
        ),
    ]
