# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_desconto_ajuste_morador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
