# Generated by Django 5.2.11 on 2026-04-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_pedidoingressorock_pix_gateway_campos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="morador",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfil_fotos/"),
        ),
    ]
