# Generated by Django 5.1.7 on 2026-04-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_pendencia_item_tipo_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovantePagamentoMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('arquivo', models.FileField(upload_to='comprovantes_pagamento/%Y/%m/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_pagamento', to='core.morador')),
            ],
            options={
                'ordering': ['-mes_referencia', '-enviado_em'],
                'unique_together': {('morador', 'mes_referencia')},
            },
        ),
    ]
