# Generated by Django 5.1.7 on 2026-04-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_comprovantepagamentomorador'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('tipo', models.CharField(choices=[('lembrete_aluguel', 'Lembrete de aluguel')], default='lembrete_aluguel', max_length=40)),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.morador')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('morador', 'mes_referencia', 'tipo')},
            },
        ),
    ]
