# Generated by Django 5.2.11 on 2026-04-14 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_notificacaomorador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("geral", "Geral"), ("setorial", "Setorial")],
                        default="geral",
                        max_length=20,
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("administrativo", "Administrativo"),
                            ("compras", "Compras"),
                            ("infraestrutura", "Infraestrutura"),
                            ("hotelaria", "Hotelaria"),
                            ("manutencao", "Manutenção"),
                            ("rock", "Rock"),
                            ("financeiro", "Financeiro"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("data", models.DateField()),
                ("horario_marcado", models.TimeField()),
                ("local", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marcada", "Marcada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="marcada",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "-horario_marcado"],
            },
        ),
        migrations.CreateModel(
            name="AtaReuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_sequencial", models.PositiveIntegerField(editable=False)),
                ("ano", models.PositiveIntegerField(editable=False)),
                ("escopo_numeracao", models.CharField(editable=False, max_length=40)),
                (
                    "identificador_formatado",
                    models.CharField(editable=False, max_length=80),
                ),
                ("horario_inicio_real", models.TimeField(blank=True, null=True)),
                ("horario_fim_real", models.TimeField(blank=True, null=True)),
                ("texto_abertura", models.TextField(blank=True, default="")),
                ("encerramento_texto", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reuniao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ata",
                        to="core.reuniao",
                    ),
                ),
            ],
            options={
                "ordering": ["-ano", "-numero_sequencial"],
                "unique_together": {("ano", "escopo_numeracao", "numero_sequencial")},
            },
        ),
    ]
