# Generated by Django 5.2.11 on 2026-04-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_reuniao_atareuniao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaAcao5W2H",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_que", models.TextField()),
                ("por_que", models.TextField(blank=True, default="")),
                ("quem", models.CharField(max_length=150)),
                ("quando", models.DateField(blank=True, null=True)),
                ("onde", models.CharField(blank=True, default="", max_length=200)),
                ("como", models.TextField(blank=True, default="")),
                ("quanto", models.CharField(blank=True, default="", max_length=120)),
                ("observacao", models.TextField(blank=True, default="")),
                ("gerou_os", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ata_reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes_5w2h",
                        to="core.atareuniao",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_5w2h",
                        to="core.ordemservico",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
    ]
