# Generated by Django 5.2.11 on 2026-04-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_reuniao_atareuniao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente", models.BooleanField(default=True)),
                ("assinatura_status", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="core.atareuniao",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes_ata",
                        to="core.morador",
                    ),
                ),
            ],
            options={
                "ordering": ["morador__ordem_hierarquia", "morador__nome"],
            },
        ),
        migrations.CreateModel(
            name="AtaTopico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                ("titulo_assunto", models.CharField(max_length=200)),
                ("desenvolvimento", models.TextField(blank=True, default="")),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos",
                        to="core.atareuniao",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("ata", "ordem"), name="unique_ata_topico_ordem")
                ],
            },
        ),
    ]
