"""
Django settings for rpf project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

if not SECRET_KEY:
    if DEBUG:
        # Chave apenas para ambiente local de desenvolvimento.
        SECRET_KEY = 'dev-only-change-me'
    else:
        raise ValueError('Defina DJANGO_SECRET_KEY no ambiente para executar em produção.')

allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
elif DEBUG:
    # Em desenvolvimento, permite acesso pela rede local.
    ALLOWED_HOSTS = ['*']
else:
    raise ValueError('Defina DJANGO_ALLOWED_HOSTS no ambiente para executar em produção.')


def _normalize_origin(raw_origin: str) -> str:
    origin = raw_origin.strip()
    if not origin:
        return ''
    if '://' not in origin:
        origin = f'https://{origin}'
    parsed = urlparse(origin)
    if parsed.scheme not in ('http', 'https') or not parsed.netloc:
        raise ValueError(
            f'Origem CSRF inválida: "{raw_origin}". Use formato "https://dominio".'
        )
    return f'{parsed.scheme}://{parsed.netloc}'


csrf_origins = []
csrf_trusted_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_env:
    csrf_origins.extend(
        _normalize_origin(origin)
        for origin in csrf_trusted_env.split(',')
        if origin.strip()
    )

render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_external_hostname:
    csrf_origins.append(_normalize_origin(render_external_hostname))

CSRF_TRUSTED_ORIGINS = sorted(set(csrf_origins))

if not DEBUG:
    invalid_non_https_origins = [
        origin for origin in CSRF_TRUSTED_ORIGINS
        if urlparse(origin).scheme != 'https'
    ]
    if invalid_non_https_origins:
        raise ValueError(
            'Em produção, CSRF_TRUSTED_ORIGINS deve conter apenas origens HTTPS.'
        )

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Inicie com 86400 (1 dia) e eleve para 31536000 (1 ano) após validar HTTPS.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '86400'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Ative preload quando o domínio e subdomínios estiverem prontos para HSTS.
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').lower() == 'true'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rpf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rpf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB por requisicao
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # 2MB por arquivo em memoria

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

PIX_PSP_BASE_URL = os.getenv('PIX_PSP_BASE_URL', '')
PIX_PSP_API_TOKEN = os.getenv('PIX_PSP_API_TOKEN', '')
PIX_PSP_TIMEOUT = int(os.getenv('PIX_PSP_TIMEOUT', '10'))
PIX_WEBHOOK_SECRET = os.getenv('PIX_WEBHOOK_SECRET', '')
