from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('acessos/', views.gerenciar_acessos, name='gerenciar_acessos'),
    path('', views.home, name='home'),
    path('calendario/', views.calendario, name='calendario'),
    path('reunioes/', views.reunioes, name='reunioes'),
    path('reunioes/<int:reuniao_id>/ata/adicionar/', views.adicionar_ata_reuniao, name='adicionar_ata_reuniao'),
    path('reunioes/<int:reuniao_id>/ata/', views.editar_ata_reuniao, name='editar_ata_reuniao'),
    path('reunioes/<int:reuniao_id>/ata/pdf/', views.baixar_ata_pdf, name='baixar_ata_pdf'),
    path('perfil/', views.perfil, name='perfil'),
    path('moradores/', views.moradores, name='moradores'),
    path('moradores/exportar/', views.exportar_moradores_csv, name='exportar_moradores_csv'),
    path('financeiro/', views.financeiro, name='financeiro'),
    path('financeiro/exportar/', views.exportar_financeiro_csv, name='exportar_financeiro_csv'),
    path('financeiro/notas/<int:nota_id>/pagar/', views.pagar_nota, name='pagar_nota'),
    path('financeiro/parcelas/<int:parcela_id>/pagar/', views.pagar_parcela, name='pagar_parcela'),
    path(
        'financeiro/moradores/<int:morador_id>/comprovante/',
        views.anexar_comprovante_pagamento,
        name='anexar_comprovante_pagamento',
    ),
    path(
        'financeiro/comprovantes/<int:comprovante_id>/ver/',
        views.ver_comprovante_pagamento,
        name='ver_comprovante_pagamento',
    ),
    path('financeiro/parcelas/<int:parcela_id>/editar/', views.editar_parcela, name='editar_parcela'),
    path('financeiro/parcelas/<int:parcela_id>/rateio/', views.editar_rateio_parcela, name='editar_rateio_parcela'),
    path('compras/', views.compras, name='compras'),
    path('configuracoes/formularios/', views.configurar_formularios, name='configurar_formularios'),
    path('configuracoes/listas/', views.configurar_listas, name='configurar_listas'),
    path('configuracoes/casa/', views.configurar_listas, name='configurar_casa'),
    path('compras/editar/<int:nota_id>/', views.editar_nota_compra, name='editar_nota_compra'),
    path('compras/exportar/', views.exportar_compras_csv, name='exportar_compras_csv'),
    path('rock/', views.rock, name='rock'),
    path('rock/comprar/', views.comprar_rocks, name='comprar_rocks'),
    path('rock/pix/webhook/', views.webhook_pix, name='webhook_pix'),
    path('rock/editar/<int:evento_id>/', views.editar_rock, name='editar_rock'),
    path('rock/<int:evento_id>/lotes/', views.lotes_rock, name='lotes_rock'),
    path('rock/<int:evento_id>/ingressos/', views.ingressos_rock, name='ingressos_rock'),
    path('rock/<int:evento_id>/ingressos/pdf/', views.exportar_ingressos_rock_pdf, name='exportar_ingressos_rock_pdf'),
    path('almoxarifado/', views.almoxarifado, name='almoxarifado'),
    path('almoxarifado/editar/<int:produto_id>/', views.editar_produto, name='editar_produto'),
    path('almoxarifado/exportar/', views.exportar_estoque_csv, name='exportar_estoque_csv'),
    path('almoxarifado/consumo/', views.registrar_consumo, name='registrar_consumo'),
    path('almoxarifado/consumo/historico/', views.consumo_historico, name='consumo_historico'),
    path('almoxarifado/consumo/exportar/', views.exportar_consumo_csv, name='exportar_consumo_csv'),
    path('os/', views.manutencao, name='manutencao'),
    path('os/lista/', views.lista_os, name='lista_os'),
    path('os/editar/<int:numero>/', views.editar_os, name='editar_os'),
    path('os/transferir/<int:numero>/', views.transferir_situacao_os, name='transferir_situacao_os'),
]
