from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('api/paginas/', views.api_paginas, name='api_paginas'),
    path('api/moradores/', views.api_moradores, name='api_moradores'),
    path('api/paginas/home/relatorio/', views.api_relatorio_home, name='api_relatorio_home'),
    path('api/paginas/calendario/relatorio/', views.api_relatorio_calendario, name='api_relatorio_calendario'),
    path('api/paginas/perfil/relatorio/', views.api_relatorio_perfil, name='api_relatorio_perfil'),
    path('api/paginas/moradores/relatorio/', views.api_relatorio_moradores, name='api_relatorio_moradores'),
    path('api/paginas/financeiro/relatorio/', views.api_relatorio_financeiro, name='api_relatorio_financeiro'),
    path('api/paginas/compras/relatorio/', views.api_relatorio_compras, name='api_relatorio_compras'),
    path('api/paginas/rock/relatorio/', views.api_relatorio_rock, name='api_relatorio_rock'),
    path('api/paginas/almoxarifado/relatorio/', views.api_relatorio_almoxarifado, name='api_relatorio_almoxarifado'),
    path('api/paginas/manutencao/relatorio/', views.api_relatorio_manutencao, name='api_relatorio_manutencao'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('acessos/', views.gerenciar_acessos, name='gerenciar_acessos'),
    path('', views.home, name='home'),
    path('calendario/', views.calendario, name='calendario'),
    path('perfil/', views.perfil, name='perfil'),
    path('moradores/', views.moradores, name='moradores'),
    path('moradores/exportar/', views.exportar_moradores_csv, name='exportar_moradores_csv'),
    path('financeiro/', views.financeiro, name='financeiro'),
    path('financeiro/exportar/', views.exportar_financeiro_csv, name='exportar_financeiro_csv'),
    path('financeiro/notas/<int:nota_id>/pagar/', views.pagar_nota, name='pagar_nota'),
    path('financeiro/parcelas/<int:parcela_id>/pagar/', views.pagar_parcela, name='pagar_parcela'),
    path('financeiro/parcelas/<int:parcela_id>/editar/', views.editar_parcela, name='editar_parcela'),
    path('compras/', views.compras, name='compras'),
    path('configuracoes/formularios/', views.configurar_formularios, name='configurar_formularios'),
    path('configuracoes/listas/', views.configurar_listas, name='configurar_listas'),
    path('compras/editar/<int:nota_id>/', views.editar_nota_compra, name='editar_nota_compra'),
    path('compras/exportar/', views.exportar_compras_csv, name='exportar_compras_csv'),
    path('rock/', views.rock, name='rock'),
    path('rock/editar/<int:evento_id>/', views.editar_rock, name='editar_rock'),
    path('almoxarifado/', views.almoxarifado, name='almoxarifado'),
    path('almoxarifado/editar/<int:produto_id>/', views.editar_produto, name='editar_produto'),
    path('almoxarifado/exportar/', views.exportar_estoque_csv, name='exportar_estoque_csv'),
    path('almoxarifado/consumo/', views.registrar_consumo, name='registrar_consumo'),
    path('almoxarifado/consumo/historico/', views.consumo_historico, name='consumo_historico'),
    path('almoxarifado/consumo/exportar/', views.exportar_consumo_csv, name='exportar_consumo_csv'),
    path('os/', views.manutencao, name='manutencao'),
    path('os/lista/', views.lista_os, name='lista_os'),
    path('os/editar/<int:numero>/', views.editar_os, name='editar_os'),
]
